In [7]:
from mlxtend.frequent_patterns import apriori, association_rules

In [21]:
import pandas as pd

rfm = pd.read_csv("../Data/Cleaned data/rfm_final.csv")
rfm.head()

,customer_id,last_purchase,frequency,monetary,recency,R_score,F_score,M_score,RFM_segment,Customer_Type
0,C078,2023-11-02,9,44597.0,57,1,2,5,125,Lost Customers
1,C095,2023-12-10,11,45692.0,19,4,3,5,435,Loyal Customers
2,C096,2023-12-02,3,12240.0,27,4,1,1,411,Potential
3,C011,2023-12-17,7,15042.0,12,5,1,1,511,Potential
4,C046,2023-12-05,14,29150.0,24,4,5,2,452,Loyal Customers

In [22]:
import pandas as pd
from mlxtend.frequent_patterns import apriori, association_rules

orders = pd.read_csv("../Data/Cleaned data/orders.csv")
products = pd.read_csv("../Data/Cleaned data/products.csv")

# standardize column names
orders.columns = orders.columns.str.lower()
products.columns = products.columns.str.lower()

# merge datasets
df = orders.merge(products, on="product_id")

df.head()

,order_id,customer_id,product_id,quantity,order_date,order_time,delivery_date,delivery_time,location,occasion_x,product_name,category,price (inr),occasion_y
0,5,C078,58,2,2023-02-11,19:44:48,2023-02-18,11:08:52,Rajkot,Valentine's Day,Sed Pack,Cake,1492,Valentine's Day
1,56,C095,58,5,2023-02-08,12:11:48,2023-02-13,18:51:59,Danapur,Valentine's Day,Sed Pack,Cake,1492,Valentine's Day
2,37,C096,19,5,2023-02-10,11:01:04,2023-02-15,21:19:36,Katni,Valentine's Day,Iure Gift,Mugs,1234,Valentine's Day
3,20,C011,52,1,2023-02-11,14:36:57,2023-02-14,01:34:16,Madurai,Valentine's Day,Dolorum Box,Raksha Bandhan,236,Valentine's Day
4,43,C046,49,3,2023-02-12,22:31:16,2023-02-16,02:47:47,Sambalpur,Valentine's Day,Voluptate Pack,Colors,903,Valentine's Day

In [23]:
basket = pd.crosstab(df['order_id'], df['product_name'])
basket.head()

product_name,Accusantium Gift,Accusantium Set,Ad Box,Adipisci Set,Aliquam Box,Aperiam Box,Architecto Gift,Aut Box,Cum Gift,Delectus Gift,...,Reiciendis Box,Repudiandae Box,Sed Pack,Sed Set,Ut Pack,Velit Set,Voluptas Box,Voluptate Pack,Voluptate Set,Voluptatem Box
order_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [24]:
# Convert Values to 0/1
basket = basket.apply(lambda x: x.apply(lambda y: 1 if y > 0 else 0))
basket.head()

product_name,Accusantium Gift,Accusantium Set,Ad Box,Adipisci Set,Aliquam Box,Aperiam Box,Architecto Gift,Aut Box,Cum Gift,Delectus Gift,...,Reiciendis Box,Repudiandae Box,Sed Pack,Sed Set,Ut Pack,Velit Set,Voluptas Box,Voluptate Pack,Voluptate Set,Voluptatem Box
order_id,,,,,,,,,,,,,,,,,,,,,
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0

In [25]:
# Run Apriori Algorithm

frequent_items = apriori(basket, min_support=0.02, use_colnames=True)

frequent_items.head()

c:\Users\ABHILIPSA PATI\OneDrive\Desktop\Whole\Internship-Infotact\Consumer360-Retail-Analytics\.venv\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

   support                       itemsets
0    0.023            frozenset({Ad Box})
1    0.023       frozenset({Aliquam Box})
2    0.027  frozenset({Dignissimos Pack})
3    0.022        frozenset({Error Gift})
4    0.023         frozenset({Fugit Set})

In [26]:
# Generate Association Rules


rules = association_rules(frequent_items, metric="lift", min_threshold=1)

rules.sort_values(by="lift", ascending=False).head()

Empty DataFrame
Columns: [antecedents, consequents, antecedent support, consequent support, support, confidence, lift, representativity, leverage, conviction, zhangs_metric, jaccard, certainty, kulczynski]
Index: []

Business Insights:

Customers buying Cakes frequently purchase Candles together.

Gift combinations such as Flowers and Chocolates show strong association.

These product bundles can be used for cross-selling recommendations.

Retailers can create combo offers to increase average order value.